### ISSUE TITLE
Add code style guidelines and make code match them

### ISSUE THREAD

**Issue by crshnburn** [zosconnect/zosconnect-node#1]
We need to specify code style guidelines, check if they can be enforced in the CI builds and document what they are in the contributing guidelines.

Looking at other projects they make use of [airbnb](https://github.com/airbnb/javascript) and [JSCS](http://jscs.info/overview) has some plug-ins for checking these.

**Comment by UkRobJones** [comment]
Using jscs with the airbnb preset generates 131 errors (today), which drops down to 17 after applying automatic fix. Easy enough to get these out using command line (we can add a .jscsrc file), but ideally these need to come out of CI via a new test scrpit, e.g. "test/codestyle.js".

**Comment by crshnburn** [comment]
Automated testing would be ideal. Could also consider [mocha-jscs](https://github.com/tomchentw/mocha-jscs) which would integrate with our existing tests

**Comment by UkRobJones** [comment]
mocha-jscs with airbnb preset is now running in my fork, and all code formatting/style issues have been resolved except for one consistent error which is coming out from both test modules, "Extra quotes for key". 
Searching around, I found https://github.com/airbnb/javascript/issues/257 which suggests that in most of these cases, the single quotes are not required unless you have a hyphen in the key value. I'll hold off applying that rule of thumb for further feedback.

**Comment by UkRobJones** [comment]
Looking further at this, it was the JSCS --fix which has changed the code from e.g.:
-                            "ServiceDescription": "Get the date and time from the server",
-                            "ServiceName": "dateTimeService",
-                            "ServiceProvider": "zOSConnect Reference Service Provider",
-                            "ServiceURL": "http://192.168.99.100:9080/zosConnect/services/dateTimeService"

to...

+                          'ServiceDescription': 'Get the date and time from the server',
+                          'ServiceName': 'dateTimeService',
+                          'ServiceProvider': 'zOSConnect Reference Service Provider',
+                          'ServiceURL': 'http://192.168.99.100:9080/zosConnect/services/dateTimeService',

(see https://github.com/UkRobJones/zosconnect-node/commit/07b75543c2070c885e63b1671a1aeda577a99575)

**Comment by crshnburn** [comment]
So this looks like a cut'n'paste problem when the test was created. As the nock function takes an object directly it is fine for these key values to be defined without quotes (tested locally) and that would give us a clean code style test.

**Comment by UkRobJones** [comment]
Build #7 now shows as passing https://travis-ci.org/UkRobJones/zosconnect-node/builds/82044258

**Comment by crshnburn** [comment]
Resolved by pull request #7
