### ISSUE TITLE
Getting null

### ISSUE THREAD

**Issue by cabrerachaparro** [zosconnect/zosconnect-node#19]
Hello,
I am running the following code but I am getting null. Does it means no services in the mainframe?

```
var Zos = require('zosconnect-node')

var options = {
  uri:'http://aaaa.bbb.ccc.com:8080',
  auth:{
    user: 'xxxxx',
    pass: 'xxxxx'
  }
}
var zos = new Zos(options)

zos.getServices(function(error, services){
  console.log(services)
})
```

Thanks

**Comment by crshnburn** [comment]
Hi

If there were no services in the z/OS Connect server then `services` would be an empty array. Getting `null` back suggests that there has been a problem communicating with the server and `error` will contain the details.
